### ISSUE TITLE
Violates no-multi-spaces rule

### ISSUE THREAD

**Issue by gaku-t** [gramener/eslint-plugin-template#2]
For example, for templates like
`const foo = {{ bar }};`
this plugin is actually converting "{ bar }" to spaces of the same length, resulting to curly braces with seven spaces (here I'm using quotes for spaces):
`const foo = {'''''''};`
It violates ESLint's ["no-multi-spaces" rule](https://eslint.org/docs/rules/no-multi-spaces).

**Suggestion**
I think
https://github.com/gramener/eslint-plugin-template/blob/1ee93c83bb38eed09ddb00ad7071a25efda16c1b/detemplatize.js#L2
this line should be modified to
`return '{' + match.slice(1, -1).replace(/[^\n]/g, '') + '}'`
which replaces each character (without newline) of the matched string to an empty string, rather than to a space.
And also spaces should be removed from the testing codes as below:

https://github.com/gramener/eslint-plugin-template/blob/1ee93c83bb38eed09ddb00ad7071a25efda16c1b/test/index.js#L26
should be `var target = '{};{\n};\n{\n\n\n}'` and

https://github.com/gramener/eslint-plugin-template/blob/1ee93c83bb38eed09ddb00ad7071a25efda16c1b/test/index.js#L32
should be `var target = '{\n\n\n};\n{};/*rawx*/'`

**Comment by sanand0** [comment]
We need the spaces to ensure alignment of line and column numbers. But I've made a small tweak to replace `{... spaces...}` with `{/*... spaces...*/}` instead. Hopefully that works.
