### ISSUE TITLE
template quotes within JS quotes

### ISSUE THREAD

**Issue by jayvdb** [gramener/eslint-plugin-template#5]
The following results in a parse error
```js
let activity = '{% url 'api:activity-autocomplete' %}'
```
Workaround is to use double quotes inside the templating.

**Comment by sanand0** [comment]
Please use [version 0.5.0](https://www.npmjs.com/package/eslint-plugin-template/v/0.5.0)

**Comment by jayvdb** [comment]
Thanks!  I undid all my changes to workaround this, and none caused an issue after upgrading.
