### ISSUE TITLE
Parsing error: Unterminated string constant

### ISSUE THREAD

**Issue by jayvdb** [gramener/eslint-plugin-template#6]
This triggers a `Parsing error: Unterminated string constant`
```js
{#           read: "{% url 'api:activity-roles' activity.id %}",#}
```

**Comment by sanand0** [comment]
Good catch! I didn't anticipate tags inside comments :-) Let me explore.

**Comment by sanand0** [comment]
Please use [version 0.5.0](https://www.npmjs.com/package/eslint-plugin-template/v/0.5.0)
